tasks:
  - init: cp .gitpod/docker-compose.override.yml . && make setup
    command: make start

ports:
  - port: 5173 # Vite server (serves compiled JS/CSS files in development)
    visibility: public
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
