# On GitPod, the Docker containers need to run with UID 33333 to avoid permissions errors

services:
  server:
    user: "33333"
    build:
      args:
        - UID=33333
    environment:
      - VITE_SERVER_ORIGIN=https://5173-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/static

  client:
    user: "33333"
    build:
      args:
        - UID=33333
